// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-index.ts
// ----------------------------------------------------

export { default as ParentSizeObserverCmp } from './ParentSizeObserverCmp';
export type { ParentSizeObserverCmpProps, ParentSizeObserverCmpSettings } from './ParentSizeObserverCmp';
export * from './ParentSizeObserverCmpClasses';
