// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const parentSizeObserverCmp = createUtilityClasses('ParentSizeObserverCmp', [
  
] as const);

export type ParentSizeObserverCmpClassKey = typeof parentSizeObserverCmp.slots[number];
export type ParentSizeObserverCmpClasses = typeof parentSizeObserverCmp.classes;
