// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const imageMultiCompareCmp = createUtilityClasses('ImageMultiCompareCmp', [
  'root'
] as const);

export type ImageMultiCompareCmpClassKey = typeof imageMultiCompareCmp.slots[number];
export type ImageMultiCompareCmpClasses = typeof imageMultiCompareCmp.classes;
