// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const imageCompareCmp = createUtilityClasses('ImageCompareCmp', [
  'root',
  'handle'
] as const);

export type ImageCompareCmpClassKey = typeof imageCompareCmp.slots[number];
export type ImageCompareCmpClasses = typeof imageCompareCmp.classes;
