// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const markdownRendererCmp = createUtilityClasses('MarkdownRendererCmp', [
  
] as const);

export type MarkdownRendererCmpClassKey = typeof markdownRendererCmp.slots[number];
export type MarkdownRendererCmpClasses = typeof markdownRendererCmp.classes;
