// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const codeBlockCmp = createUtilityClasses('CodeBlockCmp', [
  'root',
  'background',
  'styling'
] as const);

export type CodeBlockCmpClassKey = typeof codeBlockCmp.slots[number];
export type CodeBlockCmpClasses = typeof codeBlockCmp.classes;
