// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/utils/createUtilityClasses';

export const codeInlineCmp = createUtilityClasses('CodeInlineCmp', [
  'root'
] as const);

export type CodeInlineCmpClassKey = typeof codeInlineCmp.slots[number];
export type CodeInlineCmpClasses = typeof codeInlineCmp.classes;
