// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-index.ts
// ----------------------------------------------------

export { default as ScrollableCmp } from './ScrollableCmp';
export type { ScrollableCmpProps, ScrollableCmpSettings } from './ScrollableCmp';
export * from './ScrollableCmpClasses';
