// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const scrollableCmp = createUtilityClasses('ScrollableCmp', [
  'root',
  'viewportWrapper',
  'container',
  'row',
  'column'
] as const);

export type ScrollableCmpClassKey = typeof scrollableCmp.slots[number];
export type ScrollableCmpClasses = typeof scrollableCmp.classes;
