/**
 * ---------------------------------------------------------------------
 * ⚙️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY (except displayName)
 * ---------------------------------------------------------------------
 * This file was generated by scripts/generate-icons-manifest.ts
 * You may safely modify the "displayName" fields below; they will be
 * preserved when the manifest is regenerated.
 * ---------------------------------------------------------------------
 */
export const iconManifest = {
  "3DS_Max": {
    "type": "svg",
    "src": "/Icons/3DS_Max.svg",
    "width": 2947,
    "height": 2947,
    "aspectRatio": 1,
    "displayName": "3DS Max"
  },
  "ArtStation": {
    "type": "svg",
    "src": "/Icons/ArtStation.svg",
    "width": 208.8,
    "height": 195.9,
    "aspectRatio": 1.0658499234303216,
    "displayName": "ArtStation"
  },
  "Blender": {
    "type": "svg",
    "src": "/Icons/Blender.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "Blender"
  },
  "C": {
    "type": "svg",
    "src": "/Icons/C.svg",
    "width": 223.6851360941233,
    "height": 247.05999999999997,
    "aspectRatio": 0.9053879061528508,
    "displayName": "C"
  },
  "Claude": {
    "type": "svg",
    "src": "/Icons/Claude.svg",
    "width": 24,
    "height": 24,
    "aspectRatio": 1,
    "displayName": "Claude"
  },
  "ClaudeCode": {
    "type": "svg",
    "src": "/Icons/ClaudeCode.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "ClaudeCode"
  },
  "CMake": {
    "type": "svg",
    "src": "/Icons/CMake.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "CMake"
  },
  "cplusplus": {
    "type": "svg",
    "src": "/Icons/cplusplus.svg",
    "width": 256,
    "height": 288,
    "aspectRatio": 0.8888888888888888,
    "displayName": "C++"
  },
  "csharp": {
    "type": "svg",
    "src": "/Icons/csharp.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "C#"
  },
  "error": {
    "type": "svg",
    "src": "/Icons/error.svg",
    "width": 16,
    "height": 16,
    "aspectRatio": 1,
    "displayName": "error"
  },
  "Github": {
    "type": "svg",
    "src": "/Icons/Github.svg",
    "width": 25,
    "height": 25,
    "aspectRatio": 1,
    "displayName": "Github"
  },
  "GLM": {
    "type": "image",
    "src": "/Icons/GLM.png",
    "width": 360,
    "height": 198,
    "aspectRatio": 1.8181818181818181,
    "displayName": "GLM"
  },
  "Houdini": {
    "type": "svg",
    "src": "/Icons/Houdini.svg",
    "width": 242.81,
    "height": 250,
    "aspectRatio": 0.97124,
    "displayName": "Houdini"
  },
  "Javascript": {
    "type": "svg",
    "src": "/Icons/Javascript.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "Javascript"
  },
  "JSON": {
    "type": "svg",
    "src": "/Icons/JSON.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "JSON"
  },
  "Linkedin": {
    "type": "svg",
    "src": "/Icons/Linkedin.svg",
    "width": 382,
    "height": 382,
    "aspectRatio": 1,
    "displayName": "Linkedin"
  },
  "Lua": {
    "type": "svg",
    "src": "/Icons/Lua.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "Lua"
  },
  "Material_UI": {
    "type": "svg",
    "src": "/Icons/Material_UI.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "Material UI"
  },
  "Maya": {
    "type": "svg",
    "src": "/Icons/Maya.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "Maya"
  },
  "NodeJS": {
    "type": "svg",
    "src": "/Icons/NodeJS.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "NodeJS"
  },
  "Nsight_Graphics": {
    "type": "image",
    "src": "/Icons/Nsight_Graphics.png",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "Nsight Graphics"
  },
  "NVIDIA": {
    "type": "svg",
    "src": "/Icons/NVIDIA.svg",
    "width": 271.7,
    "height": 179.7,
    "aspectRatio": 1.511964385086255,
    "displayName": "NVIDIA"
  },
  "OpenGL": {
    "type": "svg",
    "src": "/Icons/OpenGL.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "OpenGL"
  },
  "Photoshop": {
    "type": "svg",
    "src": "/Icons/Photoshop.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "Photoshop"
  },
  "Premiere_Pro": {
    "type": "svg",
    "src": "/Icons/Premiere_Pro.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "Premiere Pro"
  },
  "Python": {
    "type": "svg",
    "src": "/Icons/Python.svg",
    "width": 32,
    "height": 32,
    "aspectRatio": 1,
    "displayName": "Python"
  },
  "React": {
    "type": "svg",
    "src": "/Icons/React.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "React"
  },
  "RenderDoc": {
    "type": "svg",
    "src": "/Icons/RenderDoc.svg",
    "width": 1024,
    "height": 1024,
    "aspectRatio": 1,
    "displayName": "RenderDoc"
  },
  "SDL": {
    "type": "svg",
    "src": "/Icons/SDL.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "SDL"
  },
  "Steam": {
    "type": "svg",
    "src": "/Icons/Steam.svg",
    "width": 32,
    "height": 32,
    "aspectRatio": 1,
    "displayName": "Steam"
  },
  "Substance_Designer": {
    "type": "svg",
    "src": "/Icons/Substance_Designer.svg",
    "width": 174.1,
    "height": 143.4,
    "aspectRatio": 1.214086471408647,
    "displayName": "Substance Designer"
  },
  "Substance_Painter": {
    "type": "svg",
    "src": "/Icons/Substance_Painter.svg",
    "width": 146.7,
    "height": 141.20000000000002,
    "aspectRatio": 1.0389518413597731,
    "displayName": "Substance Painter"
  },
  "Typescript": {
    "type": "svg",
    "src": "/Icons/Typescript.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "Typescript"
  },
  "Unity": {
    "type": "svg",
    "src": "/Icons/Unity.svg",
    "width": 256,
    "height": 263,
    "aspectRatio": 0.973384030418251,
    "displayName": "Unity",
    "invertOnDark": true
  },
  "Unreal": {
    "type": "svg",
    "src": "/Icons/Unreal.svg",
    "width": 210.4,
    "height": 210.4,
    "aspectRatio": 1,
    "displayName": "Unreal",
    "invertOnDark": true
  },
  "Visual_Studio": {
    "type": "svg",
    "src": "/Icons/Visual_Studio.svg",
    "width": 128,
    "height": 128,
    "aspectRatio": 1,
    "displayName": "Visual Studio"
  },
  "Visual_Studio_Code": {
    "type": "svg",
    "src": "/Icons/Visual_Studio_Code.svg",
    "width": 1003.9,
    "height": 995.6,
    "aspectRatio": 1.0083366813981518,
    "displayName": "VS Code"
  },
  "Vulkan": {
    "type": "svg",
    "src": "/Icons/Vulkan.svg",
    "width": 512,
    "height": 512,
    "aspectRatio": 1,
    "displayName": "Vulkan"
  },
  "ZBrush": {
    "type": "svg",
    "src": "/Icons/ZBrush.svg",
    "width": 512,
    "height": 512,
    "aspectRatio": 1,
    "displayName": "ZBrush"
  }
} as const;

export type IconManifest = typeof iconManifest;
export type IconKey = keyof typeof iconManifest;
