import type { ProjectManifest } from "@/Types/projectManifest";

/**
 * ---------------------------------------------------------------------
 * ⚙️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY (except "alt")
 * ---------------------------------------------------------------------
 * This file was generated by scripts/generate-project-manifests.ts
 * You may safely modify the "alt" fields below; they will be
 * preserved when the manifest is regenerated.
 * ---------------------------------------------------------------------
 */
export const projectManifest: ProjectManifest = {
  media: {
  "thumbnail.webp": {
    "type": "image",
    "src": "/projects/BubbleBobble/Images/thumbnail.webp",
    "width": 750,
    "height": 733,
    "aspectRatio": 1.0231923601637107,
    "alt": ""
  }
}
};
