import type { ProjectManifest } from "@/Types/projectManifest";

/**
 * ---------------------------------------------------------------------
 * ⚙️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY (except "alt")
 * ---------------------------------------------------------------------
 * This file was generated by scripts/generate-project-manifests.ts
 * You may safely modify the "alt" fields below; they will be
 * preserved when the manifest is regenerated.
 * ---------------------------------------------------------------------
 */
export const projectManifest: ProjectManifest = {
  media: {
  "Level01_001": {
    "name": "Level01_001",
    "type": "image",
    "fileType": "png",
    "src": "/projects/BubbleBobble/Images/Level01_001.png",
    "width": 764,
    "height": 669,
    "aspectRatio": 1.1420029895366217,
    "alt": "Level01 001"
  },
  "Level01_002": {
    "name": "Level01_002",
    "type": "image",
    "fileType": "png",
    "src": "/projects/BubbleBobble/Images/Level01_002.png",
    "width": 764,
    "height": 667,
    "aspectRatio": 1.1454272863568216,
    "alt": "Level01 002"
  },
  "Level02_001": {
    "name": "Level02_001",
    "type": "image",
    "fileType": "png",
    "src": "/projects/BubbleBobble/Images/Level02_001.png",
    "width": 762,
    "height": 671,
    "aspectRatio": 1.135618479880775,
    "alt": "Level02 001"
  },
  "Level03_001": {
    "name": "Level03_001",
    "type": "image",
    "fileType": "png",
    "src": "/projects/BubbleBobble/Images/Level03_001.png",
    "width": 766,
    "height": 669,
    "aspectRatio": 1.1449925261584455,
    "alt": "Level03 001"
  },
  "LoadingScreen": {
    "name": "LoadingScreen",
    "type": "image",
    "fileType": "png",
    "src": "/projects/BubbleBobble/Images/LoadingScreen.png",
    "width": 758,
    "height": 657,
    "aspectRatio": 1.1537290715372908,
    "alt": "LoadingScreen"
  },
  "MainMenu": {
    "name": "MainMenu",
    "type": "image",
    "fileType": "png",
    "src": "/projects/BubbleBobble/Images/MainMenu.png",
    "width": 757,
    "height": 671,
    "aspectRatio": 1.128166915052161,
    "alt": "MainMenu"
  },
  "Gameplay": {
    "name": "Gameplay",
    "type": "fileVideo",
    "fileType": "mkv",
    "src": "/projects/BubbleBobble/Videos/Gameplay.mkv",
    "width": 768,
    "height": 672,
    "alt": "Gameplay"
  }
}
};
