// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/utils/createUtilityClasses';

export const projectsOverviewCmp = createUtilityClasses('ProjectsOverviewCmp', [
  'root',
  'container',
  'header',
  'grid',
  'cardWrapper'
] as const);

export type ProjectsOverviewCmpClassKey = typeof projectsOverviewCmp.slots[number];
export type ProjectsOverviewCmpClasses = typeof projectsOverviewCmp.classes;
