// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-index.ts
// ----------------------------------------------------

export { default as MediaGalleryCmp } from './MediaGalleryCmp';
export type { MediaGalleryCmpProps, MediaGalleryCmpSettings } from './MediaGalleryCmp';
export * from './MediaGalleryCmpClasses';
