// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const mediaGalleryCmp = createUtilityClasses('MediaGalleryCmp', [
  'root',
  'main',
  'thumbs',
  'thumbButton',
  'videoOverlay',
  'navArrow',
  'dotStrip',
  'dotItem'
] as const);

export type MediaGalleryCmpClassKey = typeof mediaGalleryCmp.slots[number];
export type MediaGalleryCmpClasses = typeof mediaGalleryCmp.classes;
