import type { ProjectManifest } from "@/Types/projectManifest";

/**
 * ---------------------------------------------------------------------
 * ⚙️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY (except "alt")
 * ---------------------------------------------------------------------
 * This file was generated by scripts/generate-project-manifests.ts
 * You may safely modify the "alt" fields below; they will be
 * preserved when the manifest is regenerated.
 * ---------------------------------------------------------------------
 */
export const projectManifest: ProjectManifest = {
  media: {
  "gameplay_01": {
    "name": "gameplay_01",
    "type": "image",
    "fileType": "png",
    "src": "/projects/LuaCPPSnake/Images/gameplay_01.png",
    "width": 642,
    "height": 642,
    "aspectRatio": 1,
    "alt": "gameplay 01"
  },
  "gameplay_02": {
    "name": "gameplay_02",
    "type": "image",
    "fileType": "png",
    "src": "/projects/LuaCPPSnake/Images/gameplay_02.png",
    "width": 642,
    "height": 642,
    "aspectRatio": 1,
    "alt": "gameplay 02"
  },
  "game_over": {
    "name": "game_over",
    "type": "image",
    "fileType": "png",
    "src": "/projects/LuaCPPSnake/Images/game_over.png",
    "width": 642,
    "height": 642,
    "aspectRatio": 1,
    "alt": "game over"
  },
  "Gameplay": {
    "name": "Gameplay",
    "type": "fileVideo",
    "fileType": "mp4",
    "src": "/projects/LuaCPPSnake/Videos/Gameplay.mp4",
    "width": 642,
    "height": 642,
    "alt": "Gameplay"
  }
}
};
