import type { ProjectManifest } from "@/Types/projectManifest";

/**
 * ---------------------------------------------------------------------
 * ⚙️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY (except "alt")
 * ---------------------------------------------------------------------
 * This file was generated by scripts/generate-project-manifests.ts
 * You may safely modify the "alt" fields below; they will be
 * preserved when the manifest is regenerated.
 * ---------------------------------------------------------------------
 */
export const projectManifest: ProjectManifest = {
  media: {
  "gameplay_01.png": {
    "type": "image",
    "src": "/projects/LuaCPPSnake/Images/gameplay_01.png",
    "width": 644,
    "height": 641,
    "aspectRatio": 1.0046801872074882,
    "alt": ""
  }
}
};
