import type { ProjectManifest } from "@/Types/projectManifest";

/**
 * ---------------------------------------------------------------------
 * ⚙️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY (except "alt")
 * ---------------------------------------------------------------------
 * This file was generated by scripts/generate-project-manifests.ts
 * You may safely modify the "alt" fields below; they will be
 * preserved when the manifest is regenerated.
 * ---------------------------------------------------------------------
 */
export const projectManifest: ProjectManifest = {
  media: {
  "intro": {
    "name": "intro",
    "type": "image",
    "fileType": "jpg",
    "src": "/projects/Overpass2/Images/intro.jpg",
    "width": 2560,
    "height": 1440,
    "aspectRatio": 1.7777777777777777,
    "alt": "intro"
  }
}
};
