// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const barLayer = createUtilityClasses('TimelineBarLayer', [
  'root',
  'bar'
] as const);

export type TimelineBarLayerClassKey = typeof barLayer.slots[number];
export type TimelineBarLayerClasses = typeof barLayer.classes;
