// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const graphLayer = createUtilityClasses('TimelineGraphLayer', [
  'root'
] as const);

export type TimelineGraphLayerClassKey = typeof graphLayer.slots[number];
export type TimelineGraphLayerClasses = typeof graphLayer.classes;
