// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-index.ts
// ----------------------------------------------------

export { default as TimelineCmp } from './Timeline';
export type { TimelineProps as TimelineCmpProps, TimelineSettings } from './Timeline';
export * from './TimelineClasses';
