// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const timeline = createUtilityClasses('Timeline', [
  'root'
] as const);

export type TimelineClassKey = typeof timeline.slots[number];
export type TimelineClasses = typeof timeline.classes;
