// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const timelineGraphLayerCmp = createUtilityClasses('TimelineGraphLayerCmp', [
  'root'
] as const);

export type TimelineGraphLayerCmpClassKey = typeof timelineGraphLayerCmp.slots[number];
export type TimelineGraphLayerCmpClasses = typeof timelineGraphLayerCmp.classes;
