// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const timelineBarLayerCmp = createUtilityClasses('TimelineBarLayerCmp', [
  'root',
  'bar'
] as const);

export type TimelineBarLayerCmpClassKey = typeof timelineBarLayerCmp.slots[number];
export type TimelineBarLayerCmpClasses = typeof timelineBarLayerCmp.classes;
