// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const timelineSegmentSliderCmp = createUtilityClasses('TimelineSegmentSliderCmp', [
  'root',
  'bar',
  'tick',
  'handle'
] as const);

export type TimelineSegmentSliderCmpClassKey = typeof timelineSegmentSliderCmp.slots[number];
export type TimelineSegmentSliderCmpClasses = typeof timelineSegmentSliderCmp.classes;
