// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const timelineGroupCmp = createUtilityClasses('TimelineGroupCmp', [
  'groupRoot'
] as const);

export type TimelineGroupCmpClassKey = typeof timelineGroupCmp.slots[number];
export type TimelineGroupCmpClasses = typeof timelineGroupCmp.classes;
