// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const timelineTopBarCmp = createUtilityClasses('TimelineTopBarCmp', [
  'root'
] as const);

export type TimelineTopBarCmpClassKey = typeof timelineTopBarCmp.slots[number];
export type TimelineTopBarCmpClasses = typeof timelineTopBarCmp.classes;
