// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/utils/createUtilityClasses';

export const timelineCmp = createUtilityClasses('TimelineCmp', [
  'root',
  'topBar',
  'topTick',
  'layersRoot',
  'layer',
  'bar'
] as const);

export type TimelineCmpClassKey = typeof timelineCmp.slots[number];
export type TimelineCmpClasses = typeof timelineCmp.classes;
