import type { ProjectManifest } from "@/Types/projectManifest";

/**
 * ---------------------------------------------------------------------
 * ⚙️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY (except "alt")
 * ---------------------------------------------------------------------
 * This file was generated by scripts/generate-project-manifests.ts
 * You may safely modify the "alt" fields below; they will be
 * preserved when the manifest is regenerated.
 * ---------------------------------------------------------------------
 */
export const projectManifest: ProjectManifest = {
  media: {
  "Chain_Depth.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Chain_Depth.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "Chain Depth"
  },
  "Chain_Final.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Chain_Final.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "Chain Final"
  },
  "Circus_Env.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Circus_Env.webp",
    "width": 1024,
    "height": 6144,
    "aspectRatio": 0.16666666666666666,
    "alt": "Circus Env"
  },
  "Circus_Env_Cross.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Circus_Env_Cross.webp",
    "width": 4096,
    "height": 3072,
    "aspectRatio": 1.3333333333333333,
    "alt": "Circus Env Cross"
  },
  "Circus_IBL.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Circus_IBL.webp",
    "width": 64,
    "height": 384,
    "aspectRatio": 0.16666666666666666,
    "alt": "Circus IBL"
  },
  "Circus_IBL_Cross.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Circus_IBL_Cross.webp",
    "width": 256,
    "height": 192,
    "aspectRatio": 1.3333333333333333,
    "alt": "Circus IBL Cross"
  },
  "depth.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/depth.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "Depth"
  },
  "Feature_DirectionalLights.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Feature_DirectionalLights.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "Feature DirectionalLights"
  },
  "Feature_PointLight.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Feature_PointLight.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "Feature PointLight"
  },
  "Final.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Final.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "Final"
  },
  "GBuffer_Albedo.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/GBuffer_Albedo.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "GBuffer Albedo"
  },
  "GBuffer_MetallicRoughness.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/GBuffer_MetallicRoughness.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "GBuffer MetallicRoughness"
  },
  "GBuffer_WorldNormal.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/GBuffer_WorldNormal.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "GBuffer WorldNormal"
  },
  "GPU_Trace_Profiler_Timeline.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/GPU_Trace_Profiler_Timeline.webp",
    "width": 2778,
    "height": 660,
    "aspectRatio": 4.209090909090909,
    "alt": "GPU Trace Profiler Timeline"
  },
  "GPU_Trace_Profiler_Timeline_2.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/GPU_Trace_Profiler_Timeline_2.webp",
    "width": 2546,
    "height": 674,
    "aspectRatio": 3.777448071216617,
    "alt": "GPU Trace Profiler Timeline 2"
  },
  "GPU_Trace_Profiler_timeline_3.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/GPU_Trace_Profiler_timeline_3.webp",
    "width": 3710,
    "height": 706,
    "aspectRatio": 5.254957507082153,
    "alt": "GPU Trace Profiler timeline 3"
  },
  "Image_NegX.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Image_NegX.webp",
    "width": 1024,
    "height": 1024,
    "aspectRatio": 1,
    "alt": "Image NegX"
  },
  "Image_NegY.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Image_NegY.webp",
    "width": 1024,
    "height": 1024,
    "aspectRatio": 1,
    "alt": "Image NegY"
  },
  "Image_NegZ.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Image_NegZ.webp",
    "width": 1024,
    "height": 1024,
    "aspectRatio": 1,
    "alt": "Image NegZ"
  },
  "Image_PosX.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Image_PosX.webp",
    "width": 1024,
    "height": 1024,
    "aspectRatio": 1,
    "alt": "Image PosX"
  },
  "Image_PosY.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Image_PosY.webp",
    "width": 1024,
    "height": 1024,
    "aspectRatio": 1,
    "alt": "Image PosY"
  },
  "Image_PosZ.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Image_PosZ.webp",
    "width": 1024,
    "height": 1024,
    "aspectRatio": 1,
    "alt": "Image PosZ"
  },
  "LightingPass_Ambient_Albedo.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/LightingPass_Ambient_Albedo.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "LightingPass Ambient Albedo"
  },
  "LightingPass_DirAndPointLight_PBR.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/LightingPass_DirAndPointLight_PBR.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "LightingPass DirAndPointLight PBR"
  },
  "LightingPass_DirAndPointLight_PBR_Skybox.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/LightingPass_DirAndPointLight_PBR_Skybox.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "LightingPass DirAndPointLight PBR Skybox"
  },
  "LightingPass_DirAndPointLight_PBR_Skybox_IBL.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/LightingPass_DirAndPointLight_PBR_Skybox_IBL.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "LightingPass DirAndPointLight PBR Skybox IBL"
  },
  "LightingPass_DirLight_Albedo.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/LightingPass_DirLight_Albedo.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "LightingPass DirLight Albedo"
  },
  "LightingPass_DirLight_AlbedoNormal.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/LightingPass_DirLight_AlbedoNormal.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "LightingPass DirLight AlbedoNormal"
  },
  "LightingPass_DirLight_PBR.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/LightingPass_DirLight_PBR.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "LightingPass DirLight PBR"
  },
  "LightingPass_InWorldNormal.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/LightingPass_InWorldNormal.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "LightingPass InWorldNormal"
  },
  "LightingPass_Out_HDR.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/LightingPass_Out_HDR.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "LightingPass Out HDR"
  },
  "LightingPass_WorldNormal.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/LightingPass_WorldNormal.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "LightingPass WorldNormal"
  },
  "OutDoor_Env.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/OutDoor_Env.webp",
    "width": 1024,
    "height": 1024,
    "aspectRatio": 1,
    "alt": "OutDoor Env"
  },
  "OutDoor_Env_Cross-min.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/OutDoor_Env_Cross-min.webp",
    "width": 4096,
    "height": 3072,
    "aspectRatio": 1.3333333333333333,
    "alt": "OutDoor Env Cross min"
  },
  "OutDoor_Env_Cross.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/OutDoor_Env_Cross.webp",
    "width": 4096,
    "height": 3072,
    "aspectRatio": 1.3333333333333333,
    "alt": "OutDoor Env Cross"
  },
  "Outdoor_IBL.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Outdoor_IBL.webp",
    "width": 64,
    "height": 384,
    "aspectRatio": 0.16666666666666666,
    "alt": "Outdoor IBL"
  },
  "OutDoor_IBL_Cross.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/OutDoor_IBL_Cross.webp",
    "width": 256,
    "height": 192,
    "aspectRatio": 1.3333333333333333,
    "alt": "OutDoor IBL Cross"
  },
  "PostProcess_Final_Circus.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/PostProcess_Final_Circus.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "PostProcess Final Circus"
  },
  "PostProcess_Final_Outdoor.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/PostProcess_Final_Outdoor.webp",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "PostProcess Final Outdoor"
  },
  "Scrubber_DurationScale.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Scrubber_DurationScale.webp",
    "width": 2860,
    "height": 188,
    "aspectRatio": 15.212765957446809,
    "alt": "Scrubber DurationScale"
  },
  "Scrubber_Fill.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Scrubber_Fill.webp",
    "width": 1280,
    "height": 720,
    "aspectRatio": 1.7777777777777777,
    "alt": "Scrubber Fill"
  },
  "Scrubber_Overview.webp": {
    "type": "image",
    "src": "/projects/VulkanDeferredRenderer/Images/Scrubber_Overview.webp",
    "width": 2852,
    "height": 318,
    "aspectRatio": 8.968553459119496,
    "alt": "Scrubber Overview"
  }
}
};
