// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const projectCardCmp = createUtilityClasses('ProjectCardCmp', [
  'root',
  'header',
  'image',
  'techList',
  'techIcon',
  'content',
  'links',
  'description'
] as const);

export type ProjectCardCmpClassKey = typeof projectCardCmp.slots[number];
export type ProjectCardCmpClasses = typeof projectCardCmp.classes;
