// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const cardTabsCmp = createUtilityClasses('CardTabsCmp', [
  'root',
  'header',
  'tab',
  'content'
] as const);

export type CardTabsCmpClassKey = typeof cardTabsCmp.slots[number];
export type CardTabsCmpClasses = typeof cardTabsCmp.classes;
