// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-index.ts
// ----------------------------------------------------

export { default as CardTabsCmp } from './CardTabsCmp';
export type { CardTabsCmpProps, CardTabsCmpSettings } from './CardTabsCmp';
export * from './CardTabsCmpClasses';
