import type { ProjectManifest } from "@/Types/projectManifest";

/**
 * ---------------------------------------------------------------------
 * ⚙️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY (except "alt")
 * ---------------------------------------------------------------------
 * This file was generated by scripts/generate-project-manifests.ts
 * You may safely modify the "alt" fields below; they will be
 * preserved when the manifest is regenerated.
 * ---------------------------------------------------------------------
 */
export const projectManifest: ProjectManifest = {
  media: {
  "CPU_BoundingRects": {
    "name": "CPU_BoundingRects",
    "type": "image",
    "fileType": "png",
    "src": "/projects/DualRasterizer/Images/CPU_BoundingRects.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "CPU BoundingRects"
  },
  "CPU_Depth": {
    "name": "CPU_Depth",
    "type": "image",
    "fileType": "png",
    "src": "/projects/DualRasterizer/Images/CPU_Depth.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "CPU Depth"
  },
  "CPU_Diffuse": {
    "name": "CPU_Diffuse",
    "type": "image",
    "fileType": "png",
    "src": "/projects/DualRasterizer/Images/CPU_Diffuse.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "CPU Diffuse"
  },
  "CPU_Final": {
    "name": "CPU_Final",
    "type": "image",
    "fileType": "png",
    "src": "/projects/DualRasterizer/Images/CPU_Final.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "CPU Final"
  },
  "CPU_Final_NoNormalMap": {
    "name": "CPU_Final_NoNormalMap",
    "type": "image",
    "fileType": "png",
    "src": "/projects/DualRasterizer/Images/CPU_Final_NoNormalMap.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "CPU Final NoNormalMap"
  },
  "CPU_ObservedArea": {
    "name": "CPU_ObservedArea",
    "type": "image",
    "fileType": "png",
    "src": "/projects/DualRasterizer/Images/CPU_ObservedArea.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "CPU ObservedArea"
  },
  "CPU_Specular": {
    "name": "CPU_Specular",
    "type": "image",
    "fileType": "png",
    "src": "/projects/DualRasterizer/Images/CPU_Specular.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "CPU Specular"
  },
  "CPU_Specular_NoNormalMap": {
    "name": "CPU_Specular_NoNormalMap",
    "type": "image",
    "fileType": "png",
    "src": "/projects/DualRasterizer/Images/CPU_Specular_NoNormalMap.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "CPU Specular NoNormalMap"
  },
  "GPU_AnisotropicSampling": {
    "name": "GPU_AnisotropicSampling",
    "type": "image",
    "fileType": "png",
    "src": "/projects/DualRasterizer/Images/GPU_AnisotropicSampling.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "GPU AnisotropicSampling"
  },
  "GPU_Final": {
    "name": "GPU_Final",
    "type": "image",
    "fileType": "png",
    "src": "/projects/DualRasterizer/Images/GPU_Final.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "GPU Final"
  },
  "GPU_LinearSampling": {
    "name": "GPU_LinearSampling",
    "type": "image",
    "fileType": "png",
    "src": "/projects/DualRasterizer/Images/GPU_LinearSampling.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "GPU LinearSampling"
  },
  "GPU_PointSampling": {
    "name": "GPU_PointSampling",
    "type": "image",
    "fileType": "png",
    "src": "/projects/DualRasterizer/Images/GPU_PointSampling.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "GPU PointSampling"
  }
}
};
