import type { ProjectManifest } from "@/Types/projectManifest";

/**
 * ---------------------------------------------------------------------
 * ⚙️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY (except "alt")
 * ---------------------------------------------------------------------
 * This file was generated by scripts/generate-project-manifests.ts
 * You may safely modify the "alt" fields below; they will be
 * preserved when the manifest is regenerated.
 * ---------------------------------------------------------------------
 */
export const projectManifest: ProjectManifest = {
  media: {
  "CPU_BoundingRects.png": {
    "type": "image",
    "src": "/projects/DualRasterizer/Images/CPU_BoundingRects.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "CPU BoundingRects"
  },
  "CPU_Depth.png": {
    "type": "image",
    "src": "/projects/DualRasterizer/Images/CPU_Depth.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "CPU Depth"
  },
  "CPU_Diffuse.png": {
    "type": "image",
    "src": "/projects/DualRasterizer/Images/CPU_Diffuse.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "CPU Diffuse"
  },
  "CPU_Final.png": {
    "type": "image",
    "src": "/projects/DualRasterizer/Images/CPU_Final.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "CPU Final"
  },
  "CPU_FinaLNoNormalMap.png": {
    "type": "image",
    "src": "/projects/DualRasterizer/Images/CPU_FinaLNoNormalMap.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "CPU FinaLNoNormalMap"
  },
  "CPU_ObservedView.png": {
    "type": "image",
    "src": "/projects/DualRasterizer/Images/CPU_ObservedView.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "CPU ObservedView"
  },
  "CPU_Specular.png": {
    "type": "image",
    "src": "/projects/DualRasterizer/Images/CPU_Specular.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "CPU Specular"
  },
  "CPU_Specular_NoNormalMap.png": {
    "type": "image",
    "src": "/projects/DualRasterizer/Images/CPU_Specular_NoNormalMap.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "CPU Specular NoNormalMap"
  },
  "GPU_AnisotropicSampling.png": {
    "type": "image",
    "src": "/projects/DualRasterizer/Images/GPU_AnisotropicSampling.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "GPU AnisotropicSampling"
  },
  "GPU_AnisotropicSampling_NoFire.png": {
    "type": "image",
    "src": "/projects/DualRasterizer/Images/GPU_AnisotropicSampling_NoFire.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "GPU AnisotropicSampling NoFire"
  },
  "GPU_LinearSampling.png": {
    "type": "image",
    "src": "/projects/DualRasterizer/Images/GPU_LinearSampling.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "GPU LinearSampling"
  },
  "GPU_PointSampling.png": {
    "type": "image",
    "src": "/projects/DualRasterizer/Images/GPU_PointSampling.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "GPU PointSampling"
  }
}
};
