// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const segmentSliderCmp = createUtilityClasses('SegmentSliderCmp', [
  'root',
  'bar',
  'ticks',
  'tick',
  'highlight',
  'handle'
] as const);

export type SegmentSliderCmpClassKey = typeof segmentSliderCmp.slots[number];
export type SegmentSliderCmpClasses = typeof segmentSliderCmp.classes;
