// ----------------------------------------------------
// Generates index.ts files for folders containing *Cmp.tsx components
// ✅ Also validates that every styled({ name }) matches the component filename
// ✅ Re-exports types from both *Cmp.tsx and *Classes.ts files
// ----------------------------------------------------

import fs from "fs";
import path from "path";

const BASE_DIR = path.join(process.cwd(), "src", "Themes", "Default", "Components");

// Helpers
const firstLetterToLower = (str: string): string =>
  str.charAt(0).toLowerCase() + str.slice(1);

// Recursively collect all .tsx files
function getAllTsxFiles(dir: string): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...getAllTsxFiles(fullPath));
    } else if (entry.isFile() && entry.name.endsWith(".tsx")) {
      files.push(fullPath);
    }
  }

  return files;
}

// Extract all styled({ name }) occurrences
function extractStyledNames(content: string): string[] {
  const regex =
    /styled\s*\([\s\S]*?\{\s*[\s\S]*?name\s*:\s*['"]([^'"]+)['"][\s\S]*?\}\)/g;
  const names: string[] = [];
  let match;
  while ((match = regex.exec(content)) !== null) {
    names.push(match[1]);
  }
  return [...new Set(names)];
}

// Detect Props and Settings exports
function findExportedTypes(
  content: string,
  componentName: string
): { hasProps: boolean; hasSettings: boolean } {
  const propsRegex = new RegExp(
    `export\\s+(?:interface|type)\\s+${componentName}Props\\b`
  );
  const settingsRegex = new RegExp(
    `export\\s+(?:interface|type)\\s+${componentName}Settings\\b`
  );
  return {
    hasProps: propsRegex.test(content),
    hasSettings: settingsRegex.test(content),
  };
}

// Component metadata type
interface ComponentMeta {
  name: string;
  hasProps: boolean;
  hasSettings: boolean;
  styledNames: string[];
}

// ----------------------------------------------------
// Generate index.ts for a folder
// ----------------------------------------------------
function generateIndex(folderPath: string, componentsData: ComponentMeta[]): void {
  const outputPath = path.join(folderPath, "index.ts");
  const lines: string[] = [
    "// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY",
    "// Generated by scripts/generate-component-index.ts",
    "// ----------------------------------------------------\n"
  ];

  for (const { name, hasProps, hasSettings } of componentsData) {
    // Export the component
    lines.push(`export { default as ${name} } from './${name}';`);

    // Export types from the main component file
    const typeExports: string[] = [];
    if (hasProps) typeExports.push(`${name}Props`);
    if (hasSettings) typeExports.push(`${name}Settings`);
    if (typeExports.length > 0) {
      lines.push(`export type { ${typeExports.join(", ")} } from './${name}';`);
    }

    // Re-export from the generated *Classes.ts file
    lines.push(`export * from './${name}Classes';\n`);
  }

  fs.writeFileSync(outputPath, lines.join("\n"), "utf8");
}

// ----------------------------------------------------
// Main
// ----------------------------------------------------
function run(): void {
  console.log("🔍 Scanning components in:", BASE_DIR);
  const allFiles = getAllTsxFiles(BASE_DIR);
  const cmpFiles = allFiles.filter((f) => path.basename(f).endsWith("Cmp.tsx"));

  if (cmpFiles.length === 0) {
    console.log("⚠️ No *Cmp.tsx files found.");
    return;
  }

  // Group by folder
  const folders: Record<string, string[]> = {};
  for (const file of cmpFiles) {
    const folder = path.dirname(file);
    if (!folders[folder]) folders[folder] = [];
    folders[folder].push(file);
  }

  let total = 0;
  const mismatches: Array<{ file: string; expected: string; found: string[] }> = [];

  for (const [folderPath, files] of Object.entries(folders)) {
    const folderName = path.relative(BASE_DIR, folderPath);
    console.log(`\n📁 Folder: ${folderName}`);

    const componentsData: ComponentMeta[] = [];
    for (const file of files) {
      const componentName = path.basename(file, ".tsx");
      const content = fs.readFileSync(file, "utf8");

      const styledNames = extractStyledNames(content);
      const { hasProps, hasSettings } = findExportedTypes(content, componentName);

      // Validate styled({ name }) matches filename
      const invalid = styledNames.filter((n) => n !== componentName);
      if (styledNames.length > 0 && invalid.length > 0) {
        mismatches.push({
          file: path.relative(process.cwd(), file),
          expected: componentName,
          found: [...new Set(styledNames)],
        });
      } else if (styledNames.length === 0) {
        console.log(`    ⚠️  No styled({ name: ... }) found in "${componentName}"`);
      }

      componentsData.push({ name: componentName, hasProps, hasSettings, styledNames });

      console.log(`    ✅ Processed "${componentName}"`);
      console.log(
        `       ${hasProps ? "✅" : "⚠️"} props type: ${hasProps ? `${componentName}Props` : "not found"}`
      );
      console.log(
        `       ${hasSettings ? "✅" : "⚠️"} settings type: ${hasSettings ? `${componentName}Settings` : "not found"}`
      );
      if (styledNames.length) {
        console.log(`       🔎 styled({ name }): ${styledNames.join(", ")}`);
      }
    }

    generateIndex(folderPath, componentsData);
    total += files.length;
  }

  if (mismatches.length > 0) {
    console.error("\n❌ MUI `styled({ name })` mismatches detected:");
    for (const m of mismatches) {
      console.error(
        `   • ${m.file}\n` +
        `     expected name: "${m.expected}"\n` +
        `     found name(s): ${m.found.map((x) => `"${x}"`).join(", ")}\n` +
        `     ➜ Fix: update styled(..., { name: '${m.expected}', slot: '...' })`
      );
    }
    console.error(
      "\n💡 Tip: The styled `name` must EXACTLY match the component filename (e.g. MediaGalleryCmp.tsx → name: 'MediaGalleryCmp')."
    );
    process.exit(1);
  }

  console.log("\n✨ Done!");
  console.log(`📦 Total components processed: ${total}`);
}

run();
