// ----------------------------------------------------
// Generates Data/Projects/${projectName}/manifest.ts per project
// ----------------------------------------------------

import fs from "fs";
import path from "path";
import { imageSize } from "image-size";
import PATHS from '../src/Config/paths';
import { ProjectManifest, Media } from "@/Types/projectManifest";

// ---------------- Helpers ----------------
function loadExistingManifest(manifestFile: string): Media {
  if (!fs.existsSync(manifestFile)) return {};
  const content = fs.readFileSync(manifestFile, "utf8");

  // Match the object literal inside `media: { ... }`
  const match = content.match(/media:\s*({[\s\S]*?})\s*};/);
  if (!match) return {};

  try {
    // Convert TS object literal to valid JSON
    const jsonString = match[1]
      .replace(/(\w+):/g, '"$1":')
      .replace(/'/g, '"');
    return JSON.parse(jsonString);
  } catch (err) {
    console.warn(`⚠️ Failed to parse existing manifest at ${manifestFile}:`, err);
    return {};
  }
}

// ---------------- Main ----------------
import { fileURLToPath } from "url";
const projectsDir = path.join(process.cwd(), PATHS.PUBLIC_PROJECTS().value);
const dataProjectsDir = path.join(process.cwd(), PATHS.SRC_PROJECTS().value);

const projectFolders = fs
  .readdirSync(projectsDir)
  .filter((f) => fs.statSync(path.join(projectsDir, f)).isDirectory());

projectFolders.forEach((projectName) => {
  const projectPath = path.join(projectsDir, projectName);
  const imagesPath = path.join(projectPath, "Images");

  const media: Media = {};

  // Path to existing manifest file
  const projectDataDir = path.join(dataProjectsDir, projectName);
  const manifestFile = path.join(projectDataDir, "manifest.ts");
  const existingMedia = loadExistingManifest(manifestFile);

  // Collect images inside this project's Images folder
  if (fs.existsSync(imagesPath)) {
    const files = fs
      .readdirSync(imagesPath)
      .filter((file) => /\.(jpe?g|png|webp|gif|avif)$/i.test(file));

    files.forEach((file) => {
      const filepath = path.join(imagesPath, file);
      const buffer = fs.readFileSync(filepath);
      const { width, height } = imageSize(buffer);

      if (width && height) {
        const aspectRatio = width / height;
        const previousAlt =
          existingMedia[file]?.type === "image"
            ? existingMedia[file].alt
            : undefined;

        media[file] = {
          type: "image",
          src: `${PATHS.PROJECT_IMAGE({
            projectName,
            fileName: file,
          }).url().value}`,
          width,
          height,
          aspectRatio,
          alt: previousAlt ?? file.replace(/\.[^/.]+$/, "").replace(/[_-]/g, " "),
        };
      } else {
        console.warn(`⚠️ Could not read dimensions for ${filepath}`);
      }
    });
  }

  // Merge in extra.json if present
  const extraFile = path.join(projectPath, "extra.json");
  if (fs.existsSync(extraFile)) {
    try {
      const extraData = JSON.parse(fs.readFileSync(extraFile, "utf-8")) as {
        media?: Media;
      };

      if (extraData.media && typeof extraData.media === "object") {
        Object.entries(extraData.media).forEach(([key, value]) => {
          if (!media[key]) media[key] = value;
        });
      }
    } catch (err) {
      console.error(`⚠️ Failed to parse extra.json for ${projectName}:`, err);
    }
  }

  // Ensure output folder exists
  if (!fs.existsSync(projectDataDir)) {
    fs.mkdirSync(projectDataDir, { recursive: true });
  }

  // Write manifest.ts
  const fileContent = `import type { ProjectManifest } from "@/Types/projectManifest";

/**
 * ---------------------------------------------------------------------
 * ⚙️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY (except "alt")
 * ---------------------------------------------------------------------
 * This file was generated by scripts/generate-project-manifests.ts
 * You may safely modify the "alt" fields below; they will be
 * preserved when the manifest is regenerated.
 * ---------------------------------------------------------------------
 */
export const projectManifest: ProjectManifest = {
  media: ${JSON.stringify(media, null, 2)}
};
`;

  fs.writeFileSync(manifestFile, fileContent, "utf8");

  console.log(
    `✅ ${projectName}: wrote manifest.ts with ${Object.keys(media).length} items (alt preserved)`
  );
});
