import fs from "fs";
import path from "path";
import { JSDOM } from "jsdom";
import sizeOf from "image-size";

const ICONS_DIR = path.resolve("public/Icons");
const OUTPUT_FILE = path.resolve("src/Data/Icons/icons-manifest.ts");

// ---------------- Helpers ----------------
function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function getSvgDimensions(svgPath: string) {
  const content = fs.readFileSync(svgPath, "utf8");
  const { window } = new JSDOM(content, { contentType: "image/svg+xml" });
  const svg = window.document.querySelector("svg");
  if (!svg) throw new Error(`Missing <svg> in ${svgPath}`);

  let width = 0;
  let height = 0;

  const viewBox = svg.getAttribute("viewBox");
  if (viewBox) {
    const parts = viewBox.split(/[\s,]+/).map(parseFloat);
    if (parts.length >= 4) {
      width = parts[2];
      height = parts[3];
    }
  }

  if (!width || !height) {
    width = parseFloat(svg.getAttribute("width") || "0");
    height = parseFloat(svg.getAttribute("height") || "0");
  }

  if (!width || !height) {
    width = 1;
    height = 1;
  }

  return { width, height, aspectRatio: width / height };
}

function getImageDimensions(imagePath: string) {
  const buffer = fs.readFileSync(imagePath);
  const { width, height } = sizeOf(buffer);
  if (!width || !height) throw new Error(`Could not determine size for ${imagePath}`);
  return { width, height, aspectRatio: width / height };
}

function loadExistingManifest() {
  if (!fs.existsSync(OUTPUT_FILE)) return {};
  const content = fs.readFileSync(OUTPUT_FILE, "utf8");

  // Extract object literal from the TS file
  const match = content.match(/export const iconManifest = ({[\s\S]*?}) as const;/);
  if (!match) return {};

  try {
    // Convert TS object literal → valid JSON
    const jsonString = match[1]
      .replace(/(\w+):/g, '"$1":') // quote keys
      .replace(/'/g, '"');
    return JSON.parse(jsonString);
  } catch (err) {
    console.warn("⚠️ Failed to parse existing manifest, ignoring old data:", err);
    return {};
  }
}

// ---------------- Core ----------------
function generateManifest() {
  const existing = loadExistingManifest() as Record<
    string,
    {
      type: "svg" | "image";
      src: string;
      width: number;
      height: number;
      aspectRatio: number;
      displayName?: string;
    }
  >;

  const manifest: typeof existing = {};
  const files = fs.readdirSync(ICONS_DIR);

  for (const file of files) {
    if (file.startsWith(".")) continue;

    const ext = path.extname(file).toLowerCase();
    const baseName = path.basename(file, ext);
    const absPath = path.join(ICONS_DIR, file);
    const relSrc = `/Icons/${file}`;

    try {
      if (ext === ".svg" || [".png", ".jpg", ".jpeg", ".webp", ".gif"].includes(ext)) {
        const dims =
          ext === ".svg" ? getSvgDimensions(absPath) : getImageDimensions(absPath);
        const existingEntry = existing[baseName];

        // Generate display name only if not already defined
        const generatedDisplayName = baseName.replace(/_/g, " ");

        manifest[baseName] = {
          type: ext === ".svg" ? "svg" : "image",
          src: relSrc,
          width: dims.width,
          height: dims.height,
          aspectRatio: dims.aspectRatio,
          displayName: existingEntry?.displayName ?? generatedDisplayName,
        };
      } else {
        console.warn(`Skipping unsupported file: ${file}`);
      }
    } catch (err) {
      console.error(`Failed to process ${file}:`, err);
    }
  }

  for (const oldKey of Object.keys(existing)) {
    if (!manifest[oldKey]) {
      console.log(`🗑️ Removing missing icon from manifest: ${oldKey}`);
    }
  }

  // Sort alphabetically by key (nice for diffs)
  const sortedManifest = Object.fromEntries(
    Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b))
  );

  return sortedManifest;
}

function run() {
  ensureDir(path.dirname(OUTPUT_FILE));
  const manifest = generateManifest();

  const headerComment = `/**
 * ---------------------------------------------------------------------
 * ⚙️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY (except displayName)
 * ---------------------------------------------------------------------
 * This file was generated by scripts/generate-icons-manifest.ts
 * You may safely modify the "displayName" fields below; they will be
 * preserved when the manifest is regenerated.
 * ---------------------------------------------------------------------
 */
`;

  const header =
    headerComment +
    // `import type { IconManifestEntry } from "@/Types/iconManifest";\n\n` +
    `export const iconManifest = ${JSON.stringify(manifest, null, 2)} as const;\n\n` +
    `export type IconManifest = typeof iconManifest;\n` +
    `export type IconKey = keyof typeof iconManifest;\n`;

  fs.writeFileSync(OUTPUT_FILE, header, "utf8");
  console.log(`✅ Generated icon manifest → ${OUTPUT_FILE}`);
}

if (require.main === module) run();
