// ----------------------------------------------------
// ⚙️ Component Class Generator
// ----------------------------------------------------
// Scans .tsx files for `// @generate-component-classes`
// and generates `<ComponentName>Classes.ts` files next to them.
// ----------------------------------------------------
// Usage:
//   npm run ts -- scripts/generate-component-classes.ts
//   npm run ts -- scripts/generate-component-classes.ts path/to/dir
//   npm run ts -- scripts/generate-component-classes.ts path/to/file.tsx
// ----------------------------------------------------

import fs from "fs";
import path from "path";
import { glob } from "glob";
import PATHS from "../src/Config/paths";

// ----------------------------------------------------
// Base directory fallback
// ----------------------------------------------------
const DEFAULT_BASE_DIR = path.join(process.cwd(), PATHS.COMPONENTS().value);

// ----------------------------------------------------
// Helpers
// ----------------------------------------------------
const firstLetterToLower = (str: string): string =>
  str.charAt(0).toLowerCase() + str.slice(1);

/** Recursively find .tsx files in a folder */
function findTsxFiles(basePath: string): string[] {
  if (!fs.existsSync(basePath)) return [];

  // Ensure absolute path
  const absBase = path.resolve(basePath);
  const stat = fs.statSync(absBase);

  if (stat.isDirectory()) {
    // Normalize slashes and ensure proper glob pattern
    return glob.sync(path.join(absBase, "**/*.tsx").replace(/\\/g, "/"));
  } else if (stat.isFile() && absBase.endsWith(".tsx")) {
    return [absBase];
  }
  return [];
}


/** Detects the directive that triggers generation */
function hasGenerateDirective(content: string): boolean {
  return content.includes("// @generate-component-classes");
}

/** Extract slot names from makeSlot(...) calls */
function extractSlots(content: string): string[] {
  const regex =
    /makeSlot\s*\(\s*[^,]+,\s*['"]([^'"]+)['"](?:\s*,\s*\{[\s\S]*?\})?\s*\)/g;
  const slots: string[] = [];
  let match: RegExpExecArray | null;

  while ((match = regex.exec(content)) !== null) {
    slots.push(match[1]);
  }

  // Always include at least 'root'
  if (!slots.includes("root")) slots.unshift("root");

  return [...new Set(slots)];
}

/** Generate the full .ts content */
function generateClassesFile(fileBaseName: string, fullName: string, slots: string[]): string {
  const camelName = firstLetterToLower(fileBaseName);
  const slotList = slots.map((s) => `'${firstLetterToLower(s)}'`).join(",\n  ");

  return `// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const ${camelName} = createUtilityClasses('${fullName}', [
  ${slotList}
] as const);

export type ${fullName}ClassKey = typeof ${camelName}.slots[number];
export type ${fullName}Classes = typeof ${camelName}.classes;
`;
}

// ----------------------------------------------------
// Core generator logic
// ----------------------------------------------------
function generateForFile(file: string) {
  const content = fs.readFileSync(file, "utf8");
  if (!hasGenerateDirective(content)) return null;

  const dir = path.dirname(file);

  // --- Try to extract component base name from makeSlotFactory('...')
  const baseNameMatch = content.match(/makeSlotFactory\(['"]([^'"]+)['"]/);
  if (!baseNameMatch) {
    console.warn(
      `⚠️  Skipping ${path.relative(process.cwd(), file)} — missing makeSlotFactory('ComponentName', ...)`
    );
    return null;
  }
  const fullName = baseNameMatch[1]; // e.g. "TimelineGraphLayer"
  const fileBaseName = path.basename(file, ".tsx"); // e.g. "GraphLayer"
  const outFile = path.join(dir, `${fileBaseName}Classes.ts`);

  const slots = extractSlots(content);
  const generated = generateClassesFile(fileBaseName, fullName, slots);

  fs.writeFileSync(outFile, generated, "utf8");
  return { outFile, fileBaseName, fullName, slotCount: slots.length };
}

// ----------------------------------------------------
// Main entry
// ----------------------------------------------------
function run(): void {
  const arg = process.argv[2];
  const targetFiles = arg
    ? findTsxFiles(arg)
    : findTsxFiles(DEFAULT_BASE_DIR);

  if (targetFiles.length === 0) {
    console.log("⚠️ No .tsx files found for generation.");
    return;
  }

  console.log("🔍 Generating *Classes.ts for:", arg || DEFAULT_BASE_DIR);

  let total = 0;
  for (const file of targetFiles) {
    const result = generateForFile(file);
    if (result) {
      const rel = path.relative(DEFAULT_BASE_DIR, result.outFile);
      console.log(
        `✅ ${result.fullName} → ${rel} (${result.slotCount} slots)`
      );
      total++;
    }
  }

  console.log(`\n✨ Done! Processed ${total} components.`);
}

run();
