// ----------------------------------------------------
// Generates separate ${componentName}Classes.ts files
// next to each *Cmp.tsx component in the theme directory.
// ----------------------------------------------------

import fs from "fs";
import path from "path";

const BASE_DIR = path.join(process.cwd(), "src", "Themes", "Default", "Components");

// Helper
const firstLetterToLower = (str: string): string =>
  str.charAt(0).toLowerCase() + str.slice(1);

// Recursively collect all .tsx files
function getAllTsxFiles(dir: string): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...getAllTsxFiles(fullPath));
    } else if (entry.isFile() && entry.name.endsWith("Cmp.tsx")) {
      files.push(fullPath);
    }
  }

  return files;
}

// Extract slots from styled() definitions
function extractSlots(content: string): string[] {
  // Matches: makeSlot(motion.div, 'root') or makeSlot(SomeComponent, "techCategory")
  const regex = /makeSlot\s*\(\s*[^,]+,\s*['"]([^'"]+)['"](?:\s*,\s*\{[\s\S]*?\})?\s*\)/g;
  const slots: string[] = [];
  let match;

  while ((match = regex.exec(content)) !== null) {
    slots.push(match[1]);
  }

  return [...new Set(slots)];
}

// ----------------------------------------------------
// Generate `${componentName}Classes.ts` content
// ----------------------------------------------------
function generateClassesFile(componentName: string, slots: string[]): string {
  const camelName = firstLetterToLower(componentName);

  const slotList = slots.length
    ? slots.map((s) => `'${firstLetterToLower(s)}'`).join(",\n  ")
    : "";

  return `// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const ${camelName} = createUtilityClasses('${componentName}', [
  ${slotList}
] as const);

export type ${componentName}ClassKey = typeof ${camelName}.slots[number];
export type ${componentName}Classes = typeof ${camelName}.classes;
`;
}

// ----------------------------------------------------
// Main
// ----------------------------------------------------
function run(): void {
  console.log("🔍 Generating *Classes.ts files for components in:", BASE_DIR);

  const cmpFiles = getAllTsxFiles(BASE_DIR);
  if (cmpFiles.length === 0) {
    console.log("⚠️ No *Cmp.tsx files found.");
    return;
  }

  let total = 0;

  for (const file of cmpFiles) {
    const componentName = path.basename(file, ".tsx"); // e.g. MediaGalleryCmp
    const dir = path.dirname(file);
    const outFile = path.join(dir, `${componentName}Classes.ts`);

    const content = fs.readFileSync(file, "utf8");
    const slots = extractSlots(content);

    const generated = generateClassesFile(componentName, slots);
    fs.writeFileSync(outFile, generated, "utf8");

    console.log(
      `✅ ${componentName} → ${path.relative(BASE_DIR, outFile)} (${slots.length} slots)`
    );
    total++;
  }

  console.log("\n✨ Done!");
  console.log(`📦 Total components processed: ${total}`);
}

run();
