// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const iconCmp = createUtilityClasses('IconCmp', [
  'root'
] as const);

export type IconCmpClassKey = typeof iconCmp.slots[number];
export type IconCmpClasses = typeof iconCmp.classes;
