// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-index.ts
// ----------------------------------------------------

export { default as IconCmp } from './IconCmp';
export type { IconCmpProps } from './IconCmp';
export * from './IconCmpClasses';
