// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/utils/createUtilityClasses';

export const scrollBarCmp = createUtilityClasses('ScrollBarCmp', [
  'root',
  'thumb'
] as const);

export type ScrollBarCmpClassKey = typeof scrollBarCmp.slots[number];
export type ScrollBarCmpClasses = typeof scrollBarCmp.classes;
