// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/utils/createUtilityClasses';

export const projectOverviewCmp = createUtilityClasses('ProjectOverviewCmp', [
  'root',
  'textBox',
  'techCategory',
  'techCategoryItem',
  'techIconList'
] as const);

export type ProjectOverviewCmpClassKey = typeof projectOverviewCmp.slots[number];
export type ProjectOverviewCmpClasses = typeof projectOverviewCmp.classes;
