// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/utils/createUtilityClasses';

export const mediaCmp = createUtilityClasses('MediaCmp', [
  'root'
] as const);

export type MediaCmpClassKey = typeof mediaCmp.slots[number];
export type MediaCmpClasses = typeof mediaCmp.classes;
