import type { ProjectManifest } from "@/Types/projectManifest";

/**
 * ---------------------------------------------------------------------
 * ⚙️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY (except "alt")
 * ---------------------------------------------------------------------
 * This file was generated by scripts/generate-project-manifests.ts
 * You may safely modify the "alt" fields below; they will be
 * preserved when the manifest is regenerated.
 * ---------------------------------------------------------------------
 */
export const projectManifest: ProjectManifest = {
  media: {
  "example": {
    "name": "example",
    "type": "image",
    "fileType": "png",
    "src": "/projects/MayaReferencePlaneSetup/Images/example.png",
    "width": 1078,
    "height": 1011,
    "aspectRatio": 1.066271018793274,
    "alt": "example"
  },
  "demo": {
    "name": "demo",
    "type": "fileVideo",
    "fileType": "mp4",
    "src": "/projects/MayaReferencePlaneSetup/Videos/demo.mp4",
    "width": 1280,
    "height": 720,
    "alt": "demo"
  }
}
};
