import type { ProjectManifest } from "@/Types/projectManifest";

/**
 * ---------------------------------------------------------------------
 * ⚙️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY (except "alt")
 * ---------------------------------------------------------------------
 * This file was generated by scripts/generate-project-manifests.ts
 * You may safely modify the "alt" fields below; they will be
 * preserved when the manifest is regenerated.
 * ---------------------------------------------------------------------
 */
export const projectManifest: ProjectManifest = {
  media: {
  "ai-workflow": {
    "name": "ai-workflow",
    "type": "image",
    "fileType": "png",
    "src": "/projects/AIPoweredDevelopment/Images/ai-workflow.png",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7777777777777777,
    "alt": "ai workflow"
  },
  "linkedin-banner-dark": {
    "name": "linkedin-banner-dark",
    "type": "image",
    "fileType": "png",
    "src": "/projects/AIPoweredDevelopment/Images/linkedin-banner-dark.png",
    "width": 3168,
    "height": 792,
    "aspectRatio": 4,
    "alt": "linkedin banner dark"
  }
}
};
