// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const resumeCmp = createUtilityClasses('ResumeCmp', [
  'root',
  'pageContainer',
  'rightColumn',
  'header',
  'headerName',
  'headerFirstName',
  'headerLastName',
  'headerRight',
  'headerContactRow',
  'headerLabel',
  'headerContactLink',
  'headerContactText',
  'headerDivider',
  'tallSectionWrapper',
  'tallBar',
  'tallContent',
  'tallTitle',
  'tallDivider',
  'summaryText',
  'sectionHeader',
  'dividerBar',
  'entryWrapper',
  'entryRow',
  'entryTitle',
  'entryRight',
  'entrySub',
  'entryBody',
  'entryLink'
] as const);

export type ResumeCmpClassKey = typeof resumeCmp.slots[number];
export type ResumeCmpClasses = typeof resumeCmp.classes;
