// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/Utils/createUtilityClasses';

export const navbarCmp = createUtilityClasses('NavbarCmp', [
  'root',
  'topRow',
  'brand',
  'list',
  'item',
  'link',
  'underline',
  'mobileButton',
  'divider',
  'mobileMenu',
] as const);

export type NavbarCmpClassKey = typeof navbarCmp.slots[number];
export type NavbarCmpClasses = typeof navbarCmp.classes;
