// ⚙️ Auto-generated file — DO NOT EDIT MANUALLY
// Generated by scripts/generate-component-classes.ts
// ----------------------------------------------------
import { createUtilityClasses } from '@/utils/createUtilityClasses';

export const navbarCmp = createUtilityClasses('NavbarCmp', [
  'root',
  'brand',
  'list',
  'item',
  'link',
  'underline'
] as const);

export type NavbarCmpClassKey = typeof navbarCmp.slots[number];
export type NavbarCmpClasses = typeof navbarCmp.classes;
